target 'hinabian' do
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'MagicalRecord', '~> 2.3.2'
pod 'MJExtension', '~> 3.0.12'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDAutoLayout', '~> 2.1.7'
pod 'TZImagePickerController', '~> 1.9.8'

end
